//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_4_12
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_table
    {
        public int user_idd { get; set; }
        public string user_namee { get; set; }
        public string pass { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string phone_n { get; set; }
        public string city { get; set; }
    }
}
